# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=200, verbose_name='User Name')),
                ('password', models.CharField(blank=True, default=b'e10adc3949ba59abbe56e057f20f883e', max_length=200, verbose_name='Password')),
            ],
        ),
    ]
