# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 09:11
from __future__ import unicode_literals

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.png', upload_to=User.models.upload_avatar),
        ),
    ]
