# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 08:52
from __future__ import unicode_literals

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to=User.models.upload_avatar),
        ),
        migrations.AddField(
            model_name='user',
            name='sign',
            field=models.CharField(default='', max_length=200, verbose_name='Personal Signature'),
        ),
    ]
