# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20180219_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sign',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Personal Signature'),
        ),
    ]
